---
title: "R Notebook"
output:
  html_notebook: default
  pdf_document: default
---

```{r}
if (is.element('limma', installed.packages()[,1]) == FALSE) { 
install.packages('limma') }

if (is.element('edgeR', installed.packages()[,1]) == FALSE) { 
install.packages('edgeR') }

library('limma','edgeR')
```



```{r}
wd <- getwd()
WCFS1_path <- file.path(wd, "WCFS1_anno.txt")
RNA_seq_counts_path <- file.path(wd, "RNA-Seq-counts.txt")
```

```{r}
anno <- read.delim(header=TRUE, file= file.path(WCFS1_path), skip=1)
counts <- read.delim(header=TRUE, file= file.path(RNA_seq_counts_path))

head(anno)
head(counts)

# take a slice from df and change colnames
anno <- anno [,c("ORF","name")]
colnames(anno) <- c("ID","Gene")

# merge two dfs on "ID"
data <- merge(counts, anno, by.x="ID", by.y="ID", all.x=TRUE)


```

```{r}


```



```{r}
all = cbind(counts[,"WCFS1.glc.1"], counts[,"WCFS1.glc.2"],counts[,"WCFS1.rib.1"],counts[,"WCFS1.rib.2"],counts[,"NC8.glc.1"], counts[,"NC8.glc.2"],counts[,"NC8.rib.1"],counts[,"NC8.rib.2"])  
  
WCFS1all = c(counts[,"WCFS1.glc.1"], counts[,"WCFS1.glc.2"],counts[,"WCFS1.rib.1"],counts[,"WCFS1.rib.2"])
NC8all = c(counts[,"NC8.glc.1"], counts[,"NC8.glc.2"],counts[,"NC8.rib.1"],counts[,"NC8.rib.2"])

group <- c(1,1,1,1,2,2,2,2)
y <- DGEList(counts=all, group=group)
keep <- rowSums(cpm(y)>2) >= 4
y <- y[keep,]

y$samples$lib.size <- colSums(y$counts)
y <- calcNormFactors(y, method = 'TMM')
y
y$samples
plotMDS(y)

y <- estimateCommonDisp(y, verbose=TRUE)
y <- estimateTagwiseDisp(y)
plotBCV(y)

res <- exactTest(y)
fdr <- p.adjust(res$table$PValue, method="BH")
cpmres <- cpm(y)[rownames(res),]
summary(de <- decideTestsDGE(res))
```


Applying normalisation factors
```{r}
counts$WCFS1.glc.1 <- counts$WCFS1.glc.1 * y[["samples"]][["norm.factors"]][1]
counts$WCFS1.glc.2 <- counts$WCFS1.glc.2 * y[["samples"]][["norm.factors"]][2]
counts$WCFS1.rib.1 <- counts$WCFS1.rib.1 * y[["samples"]][["norm.factors"]][3]
counts$WCFS1.rib.2 <- counts$WCFS1.rib.2 * y[["samples"]][["norm.factors"]][4]

counts$NC8.glc.1 <- counts$NC8.glc.1 * y[["samples"]][["norm.factors"]][5]
counts$NC8.glc.2 <- counts$NC8.glc.2 * y[["samples"]][["norm.factors"]][6]
counts$NC8.rib.1 <- counts$NC8.rib.1 * y[["samples"]][["norm.factors"]][7]
counts$NC8.rib.2 <- counts$NC8.rib.2 * y[["samples"]][["norm.factors"]][8]


```

Fold Change:
```{r}
con <- makeContrasts(counts$WCFS1.glc.1 - counts$WCFS1.rib.1, levels="test")
qlf <- glmQLFTest(fit, contrast=con)
topTags(qlf)
```






```{r}



# write data to tsv file
write.table(data, file="WCFS1_counts.tsv", sep="\t", quote=F, row.names=F)



m2 <- as.matrix(data[,2:9])

# set headers 
rownames(m2) <- data[,"ID"]
```


```{r}
# compute correlation
cor(m2[,1],m2[,2], method="spearman")
```
```{r}
cor(m2[,2],m2[,3], method="spearman")
```
```{r}
cor(m2[,4],m2[,5], method="spearman")
```

```{r}
cor(m2[,6],m2[,7], method="spearman")
```
```{r}
hc <- hclust(dist(t(m2), method="eu"), method= "com")
plot(hc)
```
```{r}

```
```{python}
print("hello world")
```


```{r}
# make heatmap
heatmap(m2)
```
```{r}
pr <- prcomp(m2, scale.=FALSE)


```
```{r}
summary(pr)
```
```{r}
biplot(prcomp(m2), scale=T)
```